# output_dir: arianhosseini/openai_summarize_unlabelled_relabel_dpo_pythia410m_gen1
model_name: /home/toolkit/huggingface/pythia410m-tldr-dpo-1b-relbl-10k
tokenizer_name: mnoukhov/pythia410m-tldr-sft
dataset_name: arianhosseini/openai_summarize_unlabelled
train_split: train[:10000]
batch_size: 32
