dataset_name: mnoukhov/openai_summarize_comparisons_relabel_pythia1b
model_name: mnoukhov/pythia410m-tldr-sft
gold_model_name: mnoukhov/pythia1b-tldr-sft-rm 
output_dir: /home/toolkit/huggingface/arian_dir/pythia410m-tldr-dpo-1b-relbl-1brm
beta: 0.5
num_train_epochs: 3
eval_steps: 500
load_in_8bit: False
bf16: False
fp16: True
learning_rate: 1e-5
use_peft: True
lora_all_linear: True
lora_r: 8
lora_alpha: 32
lora_dropout: 0.05
gradient_accumulation_steps: 4
per_device_train_batch_size: 4
generate_greedy: True
warmup_steps: 150