model_name: mnoukhov/dpo2_pythia2.8b_tldr.yml_7692b3a0462f2e8fd35cc26b99936469
wandb_log_id: model_name
gen_dtype: bfloat16
tokenizer_name: EleutherAI/pythia-1b-deduped
dataset_name: vwxyzjn/summarize_from_feedback_tldr_3_filtered_oai_preprocessing_1706381144
gold_model_name: vwxyzjn/EleutherAI_pythia-6.9b-deduped__reward__tldr 
gold_model_revision: reward__55513__1708628552
eval_dtype: bfloat16
max_new_tokens: 128
max_length: 640
temperature: 0.010001
