model_name_or_path: /home/toolkit/trl/results/2c456ec7f9e37a8fb17b51820416d7e2/output
wandb_log_id: model_path
base_model_name: mnoukhov/pythia410m-sft-tldr
tokenizer_name: mnoukhov/pythia410m-sft-tldr
dataset_name: vwxyzjn/summarize_from_feedback_tldr_3_filtered_oai_preprocessing_1706381144
gold_model_name: cleanrl/EleutherAI_pythia-1b-deduped__reward__tldr
gold_tokenizer_name: EleutherAI/pythia-1b-deduped
max_new_tokens: 128
temperature: 0.010001
generate_batch_size: 16
eval_batch_size: 8
