model_name_or_path: mnoukhov/pythia410m-sft-tldr
model_revision: 00f4e8e4786324e5e368fb964800299749cea535
# base_model_name: mnoukhov/pythia410m-sft-tldr
# tokenizer_name: mnoukhov/pythia410m-sft-tldr
# wandb_log_id: cfb3179a6dd00a0d09b55fc900877f5b
# gen_dtype: bfloat16
dataset_name: vwxyzjn/summarize_from_feedback_tldr_3_filtered_oai_preprocessing_1706381144
llm_judge_model_name: meta-llama/Meta-Llama-3-8B-Instruct
# llm_judge_dtype: bfloat16
max_new_tokens: 128
temperature: 0.010001
