model_name: mnoukhov/pythia-2.8b-sft_hh_rlhf
model_revisions: ["main"]
# base_model_name: mnoukhov/EleutherAI_pythia-2.8b-deduped__sft__tldr_55513
# wandb_log_id: model_name
# gen_dtype: bfloat16
template: hh
dataset_name: sophiex/hh-rlhf
split: test
dataset_prompt_field: prompt
llm_judge_model_name: meta-llama/Meta-Llama-3-8B-Instruct
# llm_judge_dtype: bfloat16
max_new_tokens: 128
temperature: 0.010001
sanity_check: True
