task_type: "tldr"
## model and dataset
model_name: "mnoukhov/pythia410m-sft-tldr"
# output name
hub_model_id: "mnoukhov/pythia410m-dpo-tldr-lr1e-5"
dataset_name: mnoukhov/summarize_from_feedback_oai_preprocessing_1706381144_relabel_pythia1b
dataset_eval_split: "validation"
## dpo
learning_rate: 1e-5
lr_scheduler_type: cosine
bf16: True
gradient_accumulation_steps: 4
per_device_train_batch_size: 16
per_device_eval_batch_size: 8
num_train_epochs: 1
max_length: 640
max_prompt_length: 512
max_target_length: 128
beta: 0.05
## peft
use_peft: True
lora_r: 16
lora_alpha: 32
gradient_checkpointing: False
## save strategy
evaluation_strategy: "steps"
eval_steps: 0.2
logging_steps: 100
ddp_find_unused_parameters: False
