mode: relabel
dataset_name: vwxyzjn/summarize_from_feedback_oai_preprocessing_1706381144
output_dataset_name: mnoukhov/summarize_from_feedback_oai_preprocessing_1706381144_relabel_pythia1b
dataset_eval_split: validation
model_name: cleanrl/EleutherAI_pythia-1b-deduped__reward__tldr
tokenizer_name: EleutherAI/pythia-1b-deduped
max_length: 640
per_device_eval_batch_size: 8
bf16: True

