mode: relabel
dataset_name: mnoukhov/summarize_from_feedback_tldr3_unlabelled_vllm_pythia410m-dpo-tldr
output_dataset_name: mnoukhov/summarize_from_feedback_tldr3_unlabelled_vllm_pythia410m-dpo-tldr_relabel_pythia1b
# dataset_eval_split: validation
dataset_eval_split: ""
model_name: cleanrl/EleutherAI_pythia-1b-deduped__reward__tldr
tokenizer_name: EleutherAI/pythia-1b-deduped
max_length: 640
per_device_eval_batch_size: 8
bf16: True

