model_name: "EleutherAI/pythia-410m-deduped"
output_model_name: "sophiex/pythia-410m-sft_hh_rlhf"
dataset: "sophiex/hh-rlhf"
log_with: "wandb"
learning_rate: 1e-5
lr_scheduler_type: cosine
num_warmup_steps: 100
weight_decay: 0.05
load_in_8bit: False
fp16: True
bf16: False
streaming: False
gradient_checkpointing: False
gradient_accumulation_steps: 1
per_device_train_batch_size: 16
per_device_eval_batch_size: 8
train_completions: False
num_train_epochs: 3
seq_length: 1024
use_peft: True
lora_r: 8
lora_alpha: 32
