output_dir: summarize_from_feedback_tldr3_unlabelled_vllm_pythia410m-dpo-tldr
dataset_name: mnoukhov/summarize_from_feedback_tldr_3_filtered_oai_preprocessing_1706381144_unlabelled
lora_model: True
model_name: mnoukhov/pythia410m-dpo-tldr
tokenizer_name: mnoukhov/pythia410m-sft-tldr
revision: step1164 
base_model_name: mnoukhov/pythia410m-sft-tldr
split: train[:20000]
batch_size: 4
max_prompt_length: 512
max_new_tokens: 128
temperature: 1.0
top_p: 1.0
dtype: bfloat16
