output_name: summarize_from_feedback_tldr3_unlabelled_vllm_pythia410m-dpo-tldr
dataset_name: mnoukhov/summarize_from_feedback_tldr_3_filtered_oai_preprocessing_1706381144_unlabelled
lora_model: False
model_name: /home/toolkit/trl/results/ee3964ecdf4b89ef758918275e0fbbca/output/_merged
ref_model_name: mnoukhov/pythia410m-tldr-sft
# tokenizer_name: mnoukhov/pythia410m-sft-tldr
# base_model_name: mnoukhov/pythia410m-sft-tldr
split: train
batch_size: 4
max_prompt_length: 512
max_new_tokens: 128
temperature: 0.7
top_p: 1.0
# dtype: bfloat16
