output_dir: summarize_from_feedback_tldr3_unlabelled_vllm_dpo_costa_2.8b_bf16.yml_6e799
dataset_name: mnoukhov/summarize_from_feedback_tldr_3_filtered_oai_preprocessing_1706381144_unlabelled
model_name: mnoukhov/dpo_costa_2.8b_bf16.yml_6e799b31b95c2c4b2fc02706513357b3
lora_model: True
train_split: train[:20000]
batch_size: 4
max_prompt_length: 512
max_new_tokens: 128
temperature: 0.7
top_p: 1.0
dtype: bfloat16
