model_name: "/home/toolkit/huggingface/llama-7b-sft"
tokenizer_name: "hf-internal-testing/llama-tokenizer" 
reward_model_name: "/home/toolkit/huggingface/llama-7b-sft-rm-mine"
save_freq: 100
batch_size: 8
gradient_accumulation_steps: 8
batched_gen: True
output_dir: results/
early_stopping: True
seed: 0
total_steps: 8