model_name: "/home/toolkit/huggingface/llama-7b-sft-rm-mine"
tokenizer_name: hf-internal-testing/llama-tokenizer
just_eval: True
per_device_train_batch_size: 1
bf16: False
load_in_8bit: True
eval_subset: 500